version: "3.2"
services:
  confighub:
    container_name: dev.oracle.confighub
    build:
      context: ..
      dockerfile: dockerdev/Dockerfile
    ports:
      - "5080:5080"
      - "8008:8008"
      - "8443:443"
      - "80:80"
    volumes:
      - ../rest/target:/buildtarget:z
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5080 \
                      -Dcom.sun.management.jmxremote=true \
                      -Dcom.sun.management.jmxremote.port=8008 \
                      -Dcom.sun.management.jmxremote.rmi.port=8008 \
                      -Dcom.sun.management.jmxremote.ssl=false \
                      -Dcom.sun.management.jmxremote.authenticate=false \
                      -Dcom.sun.management.jmxremote.local.only=false \
                      -Djava.security.policy=all.policy \
                      -Djava.rmi.server.hostname=localhost"
      DB_TYPE: oracle
      DB_HOST: oracle
      DB_NAME: xe
      DB_USERNAME: system
      DB_PASSWORD: oracle
    links:
      - oracle
  oracle:
    container_name: dev.oracle.db
    image: oracleinanutshell/oracle-xe-11g
    # command: --general-log=1 --general-log-file=/var/log/mysql/mysql.log --skip-networking=0 --lower_case_table_names=1
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./database-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
