version: "3.2"
services:
  confighub:
    container_name: dev.mysql.confighub
    build:
      context: ..
      dockerfile: dockerdev/Dockerfile
    ports:
      - "5080:5080"
      - "8008:8008"
      - "8443:443"
      - "80:80"
    volumes:
      - ../rest/target:/buildtarget:z
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5080 \
                      -Dcom.sun.management.jmxremote=true \
                      -Dcom.sun.management.jmxremote.port=8008 \
                      -Dcom.sun.management.jmxremote.rmi.port=8008 \
                      -Dcom.sun.management.jmxremote.ssl=false \
                      -Dcom.sun.management.jmxremote.authenticate=false \
                      -Dcom.sun.management.jmxremote.local.only=false \
                      -Djava.security.policy=all.policy \
                      -Djava.rmi.server.hostname=localhost"
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_NAME: confighub
      DB_USERNAME: confighub
      DB_PASSWORD: confighub
    links:
      - mysql
  mysql:
    container_name: dev.mysql.db
    image: mariadb:10.8.2
    command: --general-log=1 --general-log-file=/var/log/mysql/mysql.log --skip-networking=0 --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - ./database-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
    environment:
      MYSQL_DATABASE: confighub
      MYSQL_USER: confighub
      MYSQL_PASSWORD: confighub
      MYSQL_ROOT_PASSWORD: root
